import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Github from '../assets/github.svg'
import Twitter from '../assets/twitter.svg'
import Linkedin from '../assets/linkedin.svg'
import Twitch from '../assets/twitch.svg'
import Instagram from '../assets/instagram.svg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Social Tree</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#ffffff] to-[#6e6e6e]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Image src="https://github.com/c4id3nSecurity.png" alt="" width={200} height={200} className="relative bottom-8
           rounded-full border-4 border-fuchsia-700 m-2"/>
          <h2 className="relative bottom-16 text-white"><a href="https://instagram.com">@instagram</a></h2>
          <h2 className="relative bottom-20 text-white border-solid border-2 rounded-md p-2 w-60 text-center border-violet-700"><a href="https://google.com">LINK 1</a></h2>
          <h2 className="relative bottom-28 text-white border-solid border-2 rounded-md p-2 w-60 text-center border-violet-700"><a href="https://google.com">LINK 2</a></h2>
          <h2 className="relative bottom-36 text-white border-solid border-2 rounded-md p-2 w-60 text-center border-violet-700"><a href="https://google.com">LINK 3</a></h2>
          <h2 className="relative bottom-44 text-white border-solid border-2 rounded-md p-2 w-60 text-center border-violet-700"><a href="https://google.com">LINK 4</a></h2>
          {/* <Image src={Github} alt=""/> */}
        </div>
      </main>
    </>
  );
}
